# @package _group_
arch:
  scales: 3
  channels: [64, 128, 128]
  skip_channels: [0, 0, 0]
  down_channel_overrides: [8, 8, 8]
  down_single_conv: False
  use_norm: True
  use_sigmoid: False
  use_relu_out: post  # options: 'post' (applied on returned image), 'model' (last layer in network)
  out_kernel_size: 1
  pre_out_channels: [64, 48, 32, 16]
  pre_out_kernel_size: 3
  insert_res_blocks_before: []
  approx_conv3d_at_scales: []
  approx_conv3d_low_rank_dim: 1
optim:
  lr: 1e-4
  init_lr: 1e-7
  num_warmup_iter: null
  encoder:
    lr: ${mdl.optim.lr}
    init_lr: ${mdl.optim.init_lr}
    num_warmup_iter: ${mdl.optim.num_warmup_iter}
  decoder:
    lr: ${mdl.optim.lr}
    init_lr: ${mdl.optim.init_lr}
    num_warmup_iter: ${mdl.optim.num_warmup_iter}
  iterations: 30000
  loss_function: mse
  gamma: 1e-1
return_iterates_selection:
  mode: 'standard_sequence'
  manual_iters: null
return_iterates_params_selection:
  mode: 'standard_sequence'
  manual_iters: null
show_pbar: True
torch_manual_seed: 10
use_mixed: False
