# @package _group_
epochs: 60
batch_size: 32
train_len: ${data.train_len}
lr: 0.001
lr_min: 0.0001
max_lr: 0.0005
weight_decay: 1e-5
scheduler: onecyclelr
perform_swa: True
swa:
    start_epoch: 40
    anneal_strategy: 'cos'
    anneal_epochs: 5
    swa_lr: 0.001
transforms:
  -
    name: random_brightness_contrast
    brightness_shift_min: -0.2
    brightness_shift_max: 0.2
    contrast_factor_min: 0.8
    contrast_factor_max: 1.25
    clip_min: 0.
    clip_max: null
torch_manual_seed: 1
num_data_loader_workers: 0
use_mixed: False
show_pbar: True
