defaults:
  - _global_.data: ../../cfgs/data/standard_ellipses_lotus

lr: 0.001
gamma: 5e-5
show_pbar: True
iterations: 1000
loss_function: mse
use_relu_out: False
save_reconstruction_path: ./results/TVAdam_recon/
